- name: Setup Gradle Environment
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.7'

    - name: Compile APK via Daemon
      run: |
        cd LoraReceiver
        gradle assembleDebug --no-daemon
